export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_FAIL = "REGISTER_FAIL" 

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"


export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_FAIL = "ALL_USER_FAIL"

export const USERS_DETAIL_SUCCESS = "USERS_DETAIL_SUCCESS"
export const USERS_DETAIL_REQUEST = "USERS_DETAIL_REQUEST"
export const USERS_DETAIL_FAIL = "USERS_DETAIL_FAIL"

export const UPDATE_ADMIN_USER_REQUEST = "UPDATE_ADMIN_USER_REQUEST"
export const UPDATE_ADMIN_USER_SUCCESS = "UPDATE_ADMIN_USER_SUCCESS"
export const UPDATE_ADMIN_USER_RESET = "UPDATE_ADMIN_USER_RESET"
export const UPDATE_ADMIN_USER_FAIL = "UPDATE_ADMIN_USER_FAIL"

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_RESET = "DELETE_USER_RESET"
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"

export const CLEAR_ERROR = 'CLEAR_ERROR'